import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("React UI keeps task-first Sources wording and accessible icon controls", () => {
  const app = readFileSync("src/web/src/App.tsx", "utf8");
  const shell = readFileSync("src/web/src/components/AppShell.tsx", "utf8");
  const todo = readFileSync("src/web/src/workspaces/TodoWorkspace.tsx", "utf8");
  const sources = readFileSync("src/web/src/workspaces/SourcesWorkspace.tsx", "utf8");
  const settings = readFileSync("src/web/src/workspaces/SettingsWorkspace.tsx", "utf8");
  const messages = readFileSync("src/web/src/i18n/messages.ts", "utf8");
  const i18n = readFileSync("src/web/src/i18n/use-i18n.tsx", "utf8");
  const client = readFileSync("src/web/src/api/client.ts", "utf8");
  const ui = readFileSync("src/web/src/components/ui.tsx", "utf8");
  const css = readFileSync("src/web/src/styles/globals.css", "utf8");

  assert.match(shell, /export type View = "todos" \| "sources" \| "settings"/);
  assert.match(messages, /navTodos: "待办"/);
  assert.match(messages, /navTodos: "To-Do"/);
  assert.match(messages, /language: "界面语言"/);
  assert.match(messages, /language: "Interface language"/);
  assert.doesNotMatch(shell, />Evidence</);
  assert.match(shell, /IconButton label=\{t.refresh as string\}/);
  assert.match(shell, /aria-label=\{t.organize as string\}/);
  assert.match(todo, /aria-label=\{t.organize as string\}/);
  assert.match(shell, /`Open \$\{children\}`/);
  assert.match(todo, /openSourcesFor/);
  assert.match(ui, /aria-label=\{label\}/);
  assert.match(todo, /\{t.agent\}:<\/span>/);
  assert.match(todo, /originLabel\(todo, locale\)/);
  assert.match(messages, /temporarySession: "临时会话"/);
  assert.match(app, /sourceFilter/);
  assert.match(sources, /sourceFilter/);
  assert.match(sources, /t.sourceFilter/);
  assert.match(sources, /t.searchSources/);
  assert.match(sources, /sessionGroups\(filteredSessions, locale\)/);
  assert.match(sources, /SESSION_GROUP_PREVIEW_LIMIT/);
  assert.match(sources, /OBSERVATION_PREVIEW_LIMIT/);
  assert.match(sources, /t.showAllMessages/);
  assert.match(sources, /t.loadMore/);
  assert.match(sources, /max-h-\[calc\(100vh-220px\)\]/);
  assert.match(app, /ensureSessionLoaded/);
  assert.match(settings, /scanChangedSources/);
  assert.match(messages, /sourceScanFinished: "来源扫描完成。"/);
  assert.match(settings, /Source scan failed/);
  assert.match(app, /startupStatusMessage\(startup, locale\)/);
  assert.match(app, /mergeSessions/);
  assert.match(app, /sessionId/);
  assert.match(app, /scrollIntoView/);
  assert.match(todo, /todoGroups\(props\.openTodos, t\)/);
  assert.match(todo, /OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(todo, /showMore as \(count: number\) => string/);
  assert.match(todo, /aria-expanded=\{expanded\}/);
  assert.match(todo, /originProjectLabel\(todo, locale\)/);
  assert.match(todo, /originSessionLabel\(todo, locale\)/);
  assert.match(todo, /sourceRailClass\(todo\.origin\?\.source\)/);
  assert.match(messages, /completedIgnored: "已完成 \/ 已忽略"/);
  assert.match(messages, /extractionTitle: "抽取"/);
  assert.match(settings, /advancedDiagnostics/);
  assert.match(settings, /max=\{200\}/);
  assert.match(app, /organizeStatus\(result, locale\)/);
  assert.match(settings, /startup\?\.discovery/);
  assert.match(i18n, /localStorage\.setItem\(STORAGE_KEY, locale\)/);
  assert.match(client, /userFacingError\(error: string, locale = currentLocale\(\)\)/);
  assert.match(messages, /Extraction needs setup/);
  assert.match(messages, /No actionable cards found in some sessions/);
  assert.match(messages, /Some sessions could not be processed/);
  assert.match(messages, /No Codex sessions were found in the source path/);
  assert.doesNotMatch(app, />LLM unavailable</);
  assert.match(css, /overflow-x: hidden/);
});
