import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("React UI keeps task-first Sources wording and accessible icon controls", () => {
  const app = readFileSync("src/web/src/App.tsx", "utf8");
  const client = readFileSync("src/web/src/api/client.ts", "utf8");
  const viewModel = readFileSync("src/web/src/view-model.ts", "utf8");
  const appShell = readFileSync("src/web/src/components/app-shell.tsx", "utf8");
  const todoBoard = readFileSync("src/web/src/components/todo-board.tsx", "utf8");
  const sourcesWorkspace = readFileSync("src/web/src/components/sources-workspace.tsx", "utf8");
  const settingsWorkspace = readFileSync("src/web/src/components/settings-workspace.tsx", "utf8");
  const ui = readFileSync("src/web/src/components/ui.tsx", "utf8");
  const css = readFileSync("src/web/src/styles/globals.css", "utf8");
  const frontend = [app, appShell, todoBoard, sourcesWorkspace, settingsWorkspace, ui, css].join("\n");

  assert.match(viewModel, /type View = "todos" \| "sources" \| "settings"/);
  assert.match(appShell, />To-Do</);
  assert.match(appShell, />Sources</);
  assert.doesNotMatch(frontend, />Evidence</);
  assert.match(appShell, /label="Refresh"/);
  assert.match(appShell, /aria-label="Organize all recent sessions"/);
  assert.match(todoBoard, /aria-label="Organize empty inbox"/);
  assert.match(appShell, /`Open \$\{children\}`/);
  assert.match(todoBoard, /aria-label=\{`Open sources for \$\{todo.title\}`\}/);
  assert.match(ui, /aria-label=\{label\}/);
  assert.match(ui, /function Panel/);
  assert.match(ui, /function StatusCallout/);
  assert.match(ui, /function SegmentedFilter/);
  assert.match(todoBoard, /Agent:<\/span>/);
  assert.match(todoBoard, /originLabel\(todo\)/);
  assert.match(frontend, /Temporary session/);
  assert.match(app, /sourceFilter/);
  assert.match(sourcesWorkspace, /Source filter/);
  assert.match(sourcesWorkspace, /Search sources/);
  assert.match(sourcesWorkspace, /sessionGroups\(filteredSessions\)/);
  assert.match(sourcesWorkspace, /SESSION_GROUP_PREVIEW_LIMIT/);
  assert.match(sourcesWorkspace, /OBSERVATION_PREVIEW_LIMIT/);
  assert.match(sourcesWorkspace, /Show all messages/);
  assert.match(sourcesWorkspace, /Load more/);
  assert.match(sourcesWorkspace, /max-h-\[calc\(100vh-220px\)\]/);
  assert.match(app, /ensureSessionLoaded/);
  assert.match(settingsWorkspace, /scanChangedSources/);
  assert.match(settingsWorkspace, /Source scan finished/);
  assert.match(settingsWorkspace, /Source scan failed/);
  assert.match(app, /startupStatusMessage/);
  assert.match(app, /mergeSessions/);
  assert.match(app, /sessionId/);
  assert.match(app, /scrollIntoView/);
  assert.match(todoBoard, /todoGroups\(props\.openTodos\)/);
  assert.match(todoBoard, /OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(todoBoard, /Show \{hiddenCount\} more/);
  assert.match(frontend, /aria-expanded=\{expanded\}/);
  assert.match(todoBoard, /originProjectLabel\(todo\)/);
  assert.match(todoBoard, /originSessionLabel\(todo\)/);
  assert.match(todoBoard, /sourceRailClass\(todo\.origin\?\.source\)/);
  assert.match(todoBoard, /Completed \/ ignored/);
  assert.match(settingsWorkspace, />Extraction</);
  assert.match(settingsWorkspace, /Advanced diagnostics/);
  assert.match(settingsWorkspace, /max=\{200\}/);
  assert.match(app, /organizeStatus\(result\)/);
  assert.match(client, /Extraction needs setup/);
  assert.match(client, /No actionable cards found in some sessions/);
  assert.match(client, /Some sessions could not be processed/);
  assert.match(client, /No Codex sessions were found in the source path/);
  assert.doesNotMatch(frontend, />LLM unavailable</);
  assert.match(css, /ledger-rail/);
  assert.match(css, /overflow-x: hidden/);
});
