import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("React UI keeps task-first Sources wording and accessible icon controls", () => {
  const app = readFileSync("src/web/src/App.tsx", "utf8");
  const client = readFileSync("src/web/src/api/client.ts", "utf8");
  const i18n = readFileSync("src/web/src/i18n.ts", "utf8");
  const types = readFileSync("src/web/src/types.ts", "utf8");
  const viewModel = readFileSync("src/web/src/view-model.ts", "utf8");
  const appShell = readFileSync("src/web/src/components/app-shell.tsx", "utf8");
  const todoBoard = readFileSync("src/web/src/components/todo-board.tsx", "utf8");
  const sourcesWorkspace = readFileSync("src/web/src/components/sources-workspace.tsx", "utf8");
  const observationText = readFileSync("src/web/src/components/observation-text.tsx", "utf8");
  const settingsWorkspace = readFileSync("src/web/src/components/settings-workspace.tsx", "utf8");
  const ui = readFileSync("src/web/src/components/ui.tsx", "utf8");
  const css = readFileSync("src/web/src/styles/globals.css", "utf8");
  const frontend = [app, appShell, todoBoard, sourcesWorkspace, observationText, settingsWorkspace, ui, css].join("\n");

  assert.match(viewModel, /type View = "todos" \| "sources" \| "settings"/);
  assert.match(i18n, /type Locale = "zh-CN" \| "en-US"/);
  assert.match(i18n, /const defaultLocale: Locale = "zh-CN"/);
  assert.match(i18n, /actionInbox: "行动收件箱"/);
  assert.match(i18n, /language: "界面语言"/);
  assert.match(i18n, /language: "Interface language"/);
  assert.match(i18n, /todos: "待办"/);
  assert.match(i18n, /todos: "To-Do"/);
  assert.match(i18n, /sources: "来源"/);
  assert.match(i18n, /sources: "Sources"/);
  assert.match(i18n, /discovery: "路径发现"/);
  assert.match(i18n, /discovery: "Path discovery"/);
  assert.match(i18n, /discoveryDiscovered: "已自动发现"/);
  assert.match(i18n, /discoveryConfigured: "User configured"/);
  assert.match(app, /readLocale/);
  assert.match(app, /writeLocale\(locale\)/);
  assert.match(app, /onLocale/);
  assert.match(settingsWorkspace, /aria-pressed=\{locale === option\}/);
  assert.doesNotMatch(frontend, />Evidence</);
  assert.match(appShell, /label=\{text\.refresh\}/);
  assert.match(appShell, /aria-label=\{text\.organizeAll\}/);
  assert.match(todoBoard, /aria-label=\{text\.organizeEmpty\}/);
  assert.match(appShell, /label=\{text\.openView\(text\.todos\)\}/);
  assert.match(appShell, /aria-label=\{label\}/);
  assert.match(todoBoard, /aria-label=\{text\.openTodoSources\(todo\.title\)\}/);
  assert.match(ui, /aria-label=\{label\}/);
  assert.match(ui, /function Panel/);
  assert.match(ui, /function StatusCallout/);
  assert.match(ui, /function SegmentedFilter/);
  assert.match(i18n, /agent: "Agent"/);
  assert.match(todoBoard, /originLabel\(todo, locale\)/);
  assert.match(i18n, /temporarySession: "临时会话"/);
  assert.match(i18n, /temporarySession: "Temporary session"/);
  assert.match(app, /sourceFilter/);
  assert.match(i18n, /sourceFilter: "来源筛选"/);
  assert.match(sourcesWorkspace, /text\.searchSources/);
  assert.match(sourcesWorkspace, /sessionGroups\(filteredSessions, locale\)/);
  assert.match(sourcesWorkspace, /SESSION_GROUP_PREVIEW_LIMIT/);
  assert.match(sourcesWorkspace, /OBSERVATION_PREVIEW_LIMIT/);
  assert.match(i18n, /showAllMessages: "显示全部消息"/);
  assert.match(i18n, /loadMore: "Load more"/);
  assert.match(sourcesWorkspace, /max-h-\[calc\(100vh-220px\)\]/);
  assert.match(app, /ensureSessionLoaded/);
  assert.match(settingsWorkspace, /scanChangedSources/);
  assert.match(i18n, /sourceScanFinished: "来源扫描完成。"/);
  assert.match(i18n, /sourceScanFailed: "Source scan failed: "/);
  assert.match(app, /startupStatusMessage/);
  assert.match(types, /discovery: Array/);
  assert.match(types, /status: "configured" \| "discovered" \| "missing"/);
  assert.match(settingsWorkspace, /startup\?\.discovery\.length/);
  assert.match(settingsWorkspace, /discoveryStatusLabel/);
  assert.match(app, /mergeSessions/);
  assert.match(app, /sessionId/);
  assert.match(app, /scrollIntoView/);
  assert.match(todoBoard, /todoGroups\(props\.openTodos, props\.locale\)/);
  assert.match(todoBoard, /OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(i18n, /showMore: \(count: number\) => `Show \$\{count\} more`/);
  assert.match(frontend, /aria-expanded=\{expanded\}/);
  assert.match(todoBoard, /originProjectLabel\(todo, locale\)/);
  assert.match(todoBoard, /todoEventTime\(todo\)/);
  assert.match(todoBoard, /formatRelativeTime\(todoEventTime\(todo\), locale\)/);
  assert.match(todoBoard, /sortTodosByEventTime\(group\.todos\)/);
  assert.match(todoBoard, /todo\.metadata\.completionSummary &&/);
  assert.match(todoBoard, /<details/);
  assert.doesNotMatch(todoBoard, /originSessionLabel\(todo, locale\)/);
  assert.doesNotMatch(todoBoard, /sourceRailClass\(todo\.origin\?\.source\)/);
  assert.match(sourcesWorkspace, /sessionProjectLabel\(session, locale\)/);
  assert.match(sourcesWorkspace, /sourceLabel\(session\.source, locale\)/);
  assert.match(sourcesWorkspace, /<ObservationText observation=\{observation\}/);
  assert.match(observationText, /from "react-markdown"/);
  assert.match(observationText, /skipHtml/);
  assert.match(observationText, /observation\.role === "assistant"/);
  assert.match(observationText, /sourceDisplayText\(observation\.text\)/);
  assert.doesNotMatch(observationText, /dangerouslySetInnerHTML/);
  assert.doesNotMatch(observationText, /rehype-raw/);
  assert.match(css, /\.source-markdown/);
  assert.match(i18n, /completedIgnored: "已完成 \/ 已忽略"/);
  assert.match(i18n, /happenedNow: "刚刚发生"/);
  assert.match(i18n, /happenedNow: "Happened just now"/);
  assert.match(i18n, /happenedAgo: \(value: string\) => `\$\{value\}前发生`/);
  assert.match(i18n, /happenedAgo: \(value: string\) => `Happened \$\{value\} ago`/);
  assert.match(i18n, /agentProgress: "Agent 进展"/);
  assert.match(i18n, /agentProgress: "Agent progress"/);
  assert.match(i18n, /extraction: "抽取"/);
  assert.match(i18n, /advancedDiagnostics: "高级诊断"/);
  assert.match(settingsWorkspace, /max=\{200\}/);
  assert.match(app, /organizeStatus\(result, locale\)/);
  assert.match(client, /userErrorText\(error, readLocale\(\)\)/);
  assert.match(client, /localizedUserFacingError/);
  assert.match(i18n, /llm_config_missing: "抽取需要先完成配置。"/);
  assert.match(i18n, /llm_config_missing: "Extraction needs setup."/);
  assert.match(i18n, /No actionable cards found in some sessions/);
  assert.match(i18n, /Some sessions could not be processed/);
  assert.match(i18n, /No Codex sessions were found in the source path/);
  assert.doesNotMatch(frontend, />LLM unavailable</);
  assert.match(css, /todo-description/);
  assert.match(css, /todo-meta-row/);
  assert.match(css, /overflow-x: hidden/);
});
